#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 134
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 73
#define ALIAS_COUNT 0
#define TOKEN_COUNT 40
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_mod = 2,
  anon_sym_use = 3,
  anon_sym_LT = 4,
  anon_sym_COMMA = 5,
  anon_sym_GT = 6,
  anon_sym_let = 7,
  anon_sym_mut = 8,
  anon_sym_COLON = 9,
  anon_sym_EQ = 10,
  anon_sym_SEMI = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  anon_sym_DOT = 14,
  anon_sym_COLON_COLON = 15,
  anon_sym_LBRACK = 16,
  anon_sym_RBRACK = 17,
  anon_sym_DASH = 18,
  anon_sym_BANG = 19,
  anon_sym__ = 20,
  anon_sym_i8 = 21,
  anon_sym_i16 = 22,
  anon_sym_i32 = 23,
  anon_sym_i64 = 24,
  anon_sym_i128 = 25,
  anon_sym_isize = 26,
  anon_sym_u8 = 27,
  anon_sym_u16 = 28,
  anon_sym_u32 = 29,
  anon_sym_u64 = 30,
  anon_sym_u128 = 31,
  anon_sym_usize = 32,
  anon_sym_f32 = 33,
  anon_sym_f64 = 34,
  anon_sym_e = 35,
  anon_sym_PLUS = 36,
  anon_sym_const = 37,
  sym__ident = 38,
  sym__int = 39,
  sym_document = 40,
  sym_item = 41,
  sym_mod = 42,
  sym_use = 43,
  sym_env_def = 44,
  sym_let = 45,
  sym_var_name = 46,
  sym_var_expr = 47,
  sym__expr = 48,
  sym__primary_expr = 49,
  sym_field_expr = 50,
  sym_method_expr = 51,
  sym_index_expr = 52,
  sym_unary_op = 53,
  sym_inv_op = 54,
  sym_function_call = 55,
  sym_call_params = 56,
  sym_type = 57,
  sym_function_name = 58,
  sym_num_literal = 59,
  sym__number_type_hint = 60,
  sym__scientific_exponent = 61,
  sym__qual = 62,
  sym__close = 63,
  aux_sym_document_repeat1 = 64,
  aux_sym_document_repeat2 = 65,
  aux_sym_env_def_repeat1 = 66,
  aux_sym_let_repeat1 = 67,
  aux_sym__primary_expr_repeat1 = 68,
  aux_sym__primary_expr_repeat2 = 69,
  aux_sym_type_repeat1 = 70,
  aux_sym_type_repeat2 = 71,
  aux_sym_num_literal_repeat1 = 72,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_mod] = "mod",
  [anon_sym_use] = "use",
  [anon_sym_LT] = "<",
  [anon_sym_COMMA] = ",",
  [anon_sym_GT] = ">",
  [anon_sym_let] = "let",
  [anon_sym_mut] = "mut",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DOT] = ".",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DASH] = "-",
  [anon_sym_BANG] = "!",
  [anon_sym__] = "_",
  [anon_sym_i8] = "i8",
  [anon_sym_i16] = "i16",
  [anon_sym_i32] = "i32",
  [anon_sym_i64] = "i64",
  [anon_sym_i128] = "i128",
  [anon_sym_isize] = "isize",
  [anon_sym_u8] = "u8",
  [anon_sym_u16] = "u16",
  [anon_sym_u32] = "u32",
  [anon_sym_u64] = "u64",
  [anon_sym_u128] = "u128",
  [anon_sym_usize] = "usize",
  [anon_sym_f32] = "f32",
  [anon_sym_f64] = "f64",
  [anon_sym_e] = "e",
  [anon_sym_PLUS] = "+",
  [anon_sym_const] = "const",
  [sym__ident] = "_ident",
  [sym__int] = "_int",
  [sym_document] = "document",
  [sym_item] = "item",
  [sym_mod] = "mod",
  [sym_use] = "use",
  [sym_env_def] = "env_def",
  [sym_let] = "let",
  [sym_var_name] = "var_name",
  [sym_var_expr] = "var_expr",
  [sym__expr] = "_expr",
  [sym__primary_expr] = "_primary_expr",
  [sym_field_expr] = "field_expr",
  [sym_method_expr] = "method_expr",
  [sym_index_expr] = "index_expr",
  [sym_unary_op] = "unary_op",
  [sym_inv_op] = "inv_op",
  [sym_function_call] = "function_call",
  [sym_call_params] = "call_params",
  [sym_type] = "type",
  [sym_function_name] = "function_name",
  [sym_num_literal] = "num_literal",
  [sym__number_type_hint] = "_number_type_hint",
  [sym__scientific_exponent] = "_scientific_exponent",
  [sym__qual] = "_qual",
  [sym__close] = "_close",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_document_repeat2] = "document_repeat2",
  [aux_sym_env_def_repeat1] = "env_def_repeat1",
  [aux_sym_let_repeat1] = "let_repeat1",
  [aux_sym__primary_expr_repeat1] = "_primary_expr_repeat1",
  [aux_sym__primary_expr_repeat2] = "_primary_expr_repeat2",
  [aux_sym_type_repeat1] = "type_repeat1",
  [aux_sym_type_repeat2] = "type_repeat2",
  [aux_sym_num_literal_repeat1] = "num_literal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_mod] = anon_sym_mod,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_mut] = anon_sym_mut,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym__] = anon_sym__,
  [anon_sym_i8] = anon_sym_i8,
  [anon_sym_i16] = anon_sym_i16,
  [anon_sym_i32] = anon_sym_i32,
  [anon_sym_i64] = anon_sym_i64,
  [anon_sym_i128] = anon_sym_i128,
  [anon_sym_isize] = anon_sym_isize,
  [anon_sym_u8] = anon_sym_u8,
  [anon_sym_u16] = anon_sym_u16,
  [anon_sym_u32] = anon_sym_u32,
  [anon_sym_u64] = anon_sym_u64,
  [anon_sym_u128] = anon_sym_u128,
  [anon_sym_usize] = anon_sym_usize,
  [anon_sym_f32] = anon_sym_f32,
  [anon_sym_f64] = anon_sym_f64,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_const] = anon_sym_const,
  [sym__ident] = sym__ident,
  [sym__int] = sym__int,
  [sym_document] = sym_document,
  [sym_item] = sym_item,
  [sym_mod] = sym_mod,
  [sym_use] = sym_use,
  [sym_env_def] = sym_env_def,
  [sym_let] = sym_let,
  [sym_var_name] = sym_var_name,
  [sym_var_expr] = sym_var_expr,
  [sym__expr] = sym__expr,
  [sym__primary_expr] = sym__primary_expr,
  [sym_field_expr] = sym_field_expr,
  [sym_method_expr] = sym_method_expr,
  [sym_index_expr] = sym_index_expr,
  [sym_unary_op] = sym_unary_op,
  [sym_inv_op] = sym_inv_op,
  [sym_function_call] = sym_function_call,
  [sym_call_params] = sym_call_params,
  [sym_type] = sym_type,
  [sym_function_name] = sym_function_name,
  [sym_num_literal] = sym_num_literal,
  [sym__number_type_hint] = sym__number_type_hint,
  [sym__scientific_exponent] = sym__scientific_exponent,
  [sym__qual] = sym__qual,
  [sym__close] = sym__close,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_document_repeat2] = aux_sym_document_repeat2,
  [aux_sym_env_def_repeat1] = aux_sym_env_def_repeat1,
  [aux_sym_let_repeat1] = aux_sym_let_repeat1,
  [aux_sym__primary_expr_repeat1] = aux_sym__primary_expr_repeat1,
  [aux_sym__primary_expr_repeat2] = aux_sym__primary_expr_repeat2,
  [aux_sym_type_repeat1] = aux_sym_type_repeat1,
  [aux_sym_type_repeat2] = aux_sym_type_repeat2,
  [aux_sym_num_literal_repeat1] = aux_sym_num_literal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mod] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mut] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i128] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_isize] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u128] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_usize] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [sym__ident] = {
    .visible = false,
    .named = true,
  },
  [sym__int] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_item] = {
    .visible = true,
    .named = true,
  },
  [sym_mod] = {
    .visible = true,
    .named = true,
  },
  [sym_use] = {
    .visible = true,
    .named = true,
  },
  [sym_env_def] = {
    .visible = true,
    .named = true,
  },
  [sym_let] = {
    .visible = true,
    .named = true,
  },
  [sym_var_name] = {
    .visible = true,
    .named = true,
  },
  [sym_var_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym__primary_expr] = {
    .visible = false,
    .named = true,
  },
  [sym_field_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_method_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_index_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_op] = {
    .visible = true,
    .named = true,
  },
  [sym_inv_op] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_call_params] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_function_name] = {
    .visible = true,
    .named = true,
  },
  [sym_num_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__number_type_hint] = {
    .visible = false,
    .named = true,
  },
  [sym__scientific_exponent] = {
    .visible = false,
    .named = true,
  },
  [sym__qual] = {
    .visible = false,
    .named = true,
  },
  [sym__close] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_document_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_env_def_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_let_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__primary_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__primary_expr_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_num_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '\n', 33,
        '!', 53,
        '(', 46,
        ')', 47,
        '+', 70,
        ',', 37,
        '-', 52,
        '.', 48,
        ':', 43,
        ';', 45,
        '<', 36,
        '=', 44,
        '>', 38,
        '[', 50,
        ']', 51,
        '_', 54,
        'c', 24,
        'e', 69,
        'f', 9,
        'i', 2,
        'l', 18,
        'm', 25,
        'u', 3,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 53,
        '(', 46,
        ')', 47,
        ',', 37,
        '-', 52,
        '.', 48,
        ':', 15,
        ';', 45,
        '<', 36,
        '=', 44,
        '>', 38,
        '[', 50,
        ']', 51,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 2:
      if (lookahead == '1') ADVANCE(5);
      if (lookahead == '3') ADVANCE(6);
      if (lookahead == '6') ADVANCE(11);
      if (lookahead == '8') ADVANCE(55);
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 3:
      if (lookahead == '1') ADVANCE(8);
      if (lookahead == '3') ADVANCE(7);
      if (lookahead == '6') ADVANCE(12);
      if (lookahead == '8') ADVANCE(61);
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == '2') ADVANCE(67);
      END_STATE();
    case 5:
      if (lookahead == '2') ADVANCE(13);
      if (lookahead == '6') ADVANCE(56);
      END_STATE();
    case 6:
      if (lookahead == '2') ADVANCE(57);
      END_STATE();
    case 7:
      if (lookahead == '2') ADVANCE(63);
      END_STATE();
    case 8:
      if (lookahead == '2') ADVANCE(14);
      if (lookahead == '6') ADVANCE(62);
      END_STATE();
    case 9:
      if (lookahead == '3') ADVANCE(4);
      if (lookahead == '6') ADVANCE(10);
      END_STATE();
    case 10:
      if (lookahead == '4') ADVANCE(68);
      END_STATE();
    case 11:
      if (lookahead == '4') ADVANCE(58);
      END_STATE();
    case 12:
      if (lookahead == '4') ADVANCE(64);
      END_STATE();
    case 13:
      if (lookahead == '8') ADVANCE(59);
      END_STATE();
    case 14:
      if (lookahead == '8') ADVANCE(65);
      END_STATE();
    case 15:
      if (lookahead == ':') ADVANCE(49);
      END_STATE();
    case 16:
      if (lookahead == ':') ADVANCE(42);
      if (lookahead == '=') ADVANCE(44);
      if (lookahead == 'm') ADVANCE(73);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(34);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(35);
      if (lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(30);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(17);
      if (lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(29);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(71);
      END_STATE();
    case 30:
      if (lookahead == 'z') ADVANCE(20);
      END_STATE();
    case 31:
      if (lookahead == 'z') ADVANCE(21);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_mod);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_mut);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_mut);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(49);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_i8);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_i16);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_i32);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_i64);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_i128);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_isize);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_u8);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_u16);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_u32);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_u64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_u128);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_usize);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_f32);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_f64);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_e);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == 't') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == 'u') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym__ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym__int);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(75);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 16},
  [93] = {.lex_state = 1},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 1},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 1},
  [104] = {.lex_state = 1},
  [105] = {.lex_state = 1},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 16},
  [109] = {.lex_state = 16},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 1},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 1},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 16},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 1},
  [121] = {.lex_state = 1},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 1},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 1},
  [132] = {.lex_state = 1},
  [133] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_mod] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_mut] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_i8] = ACTIONS(1),
    [anon_sym_i16] = ACTIONS(1),
    [anon_sym_i32] = ACTIONS(1),
    [anon_sym_i64] = ACTIONS(1),
    [anon_sym_i128] = ACTIONS(1),
    [anon_sym_isize] = ACTIONS(1),
    [anon_sym_u8] = ACTIONS(1),
    [anon_sym_u16] = ACTIONS(1),
    [anon_sym_u32] = ACTIONS(1),
    [anon_sym_u64] = ACTIONS(1),
    [anon_sym_u128] = ACTIONS(1),
    [anon_sym_usize] = ACTIONS(1),
    [anon_sym_f32] = ACTIONS(1),
    [anon_sym_f64] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [sym__int] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(128),
    [sym_item] = STATE(42),
    [sym_mod] = STATE(65),
    [sym_use] = STATE(65),
    [sym_let] = STATE(65),
    [aux_sym_document_repeat1] = STATE(39),
    [aux_sym_document_repeat2] = STATE(42),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym_mod] = ACTIONS(7),
    [anon_sym_use] = ACTIONS(9),
    [anon_sym_let] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(15), 1,
      anon_sym__,
    ACTIONS(19), 1,
      anon_sym_e,
    ACTIONS(21), 1,
      sym__int,
    STATE(7), 1,
      aux_sym_num_literal_repeat1,
    STATE(9), 1,
      sym__scientific_exponent,
    STATE(53), 1,
      sym__number_type_hint,
    ACTIONS(13), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(17), 14,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_i128,
      anon_sym_isize,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_u128,
      anon_sym_usize,
      anon_sym_f32,
      anon_sym_f64,
  [44] = 8,
    ACTIONS(19), 1,
      anon_sym_e,
    ACTIONS(25), 1,
      anon_sym_DOT,
    ACTIONS(27), 1,
      anon_sym__,
    STATE(5), 1,
      sym__scientific_exponent,
    STATE(6), 1,
      aux_sym_num_literal_repeat1,
    STATE(58), 1,
      sym__number_type_hint,
    ACTIONS(23), 6,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(29), 14,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_i128,
      anon_sym_isize,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_u128,
      anon_sym_usize,
      anon_sym_f32,
      anon_sym_f64,
  [87] = 7,
    ACTIONS(19), 1,
      anon_sym_e,
    ACTIONS(33), 1,
      anon_sym__,
    STATE(8), 1,
      sym__scientific_exponent,
    STATE(10), 1,
      aux_sym_num_literal_repeat1,
    STATE(46), 1,
      sym__number_type_hint,
    ACTIONS(31), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(35), 14,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_i128,
      anon_sym_isize,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_u128,
      anon_sym_usize,
      anon_sym_f32,
      anon_sym_f64,
  [128] = 5,
    ACTIONS(15), 1,
      anon_sym__,
    STATE(7), 1,
      aux_sym_num_literal_repeat1,
    STATE(53), 1,
      sym__number_type_hint,
    ACTIONS(13), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(17), 14,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_i128,
      anon_sym_isize,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_u128,
      anon_sym_usize,
      anon_sym_f32,
      anon_sym_f64,
  [163] = 5,
    ACTIONS(37), 1,
      anon_sym__,
    STATE(12), 1,
      aux_sym_num_literal_repeat1,
    STATE(53), 1,
      sym__number_type_hint,
    ACTIONS(13), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(17), 14,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_i128,
      anon_sym_isize,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_u128,
      anon_sym_usize,
      anon_sym_f32,
      anon_sym_f64,
  [198] = 5,
    ACTIONS(37), 1,
      anon_sym__,
    STATE(12), 1,
      aux_sym_num_literal_repeat1,
    STATE(46), 1,
      sym__number_type_hint,
    ACTIONS(31), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(35), 14,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_i128,
      anon_sym_isize,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_u128,
      anon_sym_usize,
      anon_sym_f32,
      anon_sym_f64,
  [233] = 5,
    ACTIONS(41), 1,
      anon_sym__,
    STATE(11), 1,
      aux_sym_num_literal_repeat1,
    STATE(57), 1,
      sym__number_type_hint,
    ACTIONS(39), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(43), 14,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_i128,
      anon_sym_isize,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_u128,
      anon_sym_usize,
      anon_sym_f32,
      anon_sym_f64,
  [268] = 5,
    ACTIONS(33), 1,
      anon_sym__,
    STATE(10), 1,
      aux_sym_num_literal_repeat1,
    STATE(46), 1,
      sym__number_type_hint,
    ACTIONS(31), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(35), 14,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_i128,
      anon_sym_isize,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_u128,
      anon_sym_usize,
      anon_sym_f32,
      anon_sym_f64,
  [303] = 5,
    ACTIONS(37), 1,
      anon_sym__,
    STATE(12), 1,
      aux_sym_num_literal_repeat1,
    STATE(57), 1,
      sym__number_type_hint,
    ACTIONS(39), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(43), 14,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_i128,
      anon_sym_isize,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_u128,
      anon_sym_usize,
      anon_sym_f32,
      anon_sym_f64,
  [338] = 5,
    ACTIONS(37), 1,
      anon_sym__,
    STATE(12), 1,
      aux_sym_num_literal_repeat1,
    STATE(62), 1,
      sym__number_type_hint,
    ACTIONS(45), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(47), 14,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_i128,
      anon_sym_isize,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_u128,
      anon_sym_usize,
      anon_sym_f32,
      anon_sym_f64,
  [373] = 3,
    ACTIONS(51), 1,
      anon_sym__,
    STATE(12), 1,
      aux_sym_num_literal_repeat1,
    ACTIONS(49), 21,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_i128,
      anon_sym_isize,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_u128,
      anon_sym_usize,
      anon_sym_f32,
      anon_sym_f64,
  [403] = 1,
    ACTIONS(54), 22,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym__,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_i128,
      anon_sym_isize,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_u128,
      anon_sym_usize,
      anon_sym_f32,
      anon_sym_f64,
  [428] = 1,
    ACTIONS(56), 22,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym__,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_i128,
      anon_sym_isize,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_u128,
      anon_sym_usize,
      anon_sym_f32,
      anon_sym_f64,
  [453] = 10,
    ACTIONS(58), 1,
      anon_sym_GT,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_DASH,
    ACTIONS(64), 1,
      anon_sym_BANG,
    ACTIONS(66), 1,
      sym__ident,
    ACTIONS(68), 1,
      sym__int,
    STATE(116), 1,
      sym_function_name,
    STATE(102), 2,
      sym__expr,
      sym__primary_expr,
    STATE(29), 3,
      sym_unary_op,
      sym_inv_op,
      aux_sym__primary_expr_repeat1,
    STATE(37), 3,
      sym_var_expr,
      sym_function_call,
      sym_num_literal,
  [489] = 10,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_DASH,
    ACTIONS(64), 1,
      anon_sym_BANG,
    ACTIONS(66), 1,
      sym__ident,
    ACTIONS(68), 1,
      sym__int,
    ACTIONS(70), 1,
      anon_sym_GT,
    STATE(116), 1,
      sym_function_name,
    STATE(97), 2,
      sym__expr,
      sym__primary_expr,
    STATE(29), 3,
      sym_unary_op,
      sym_inv_op,
      aux_sym__primary_expr_repeat1,
    STATE(37), 3,
      sym_var_expr,
      sym_function_call,
      sym_num_literal,
  [525] = 10,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_DASH,
    ACTIONS(64), 1,
      anon_sym_BANG,
    ACTIONS(66), 1,
      sym__ident,
    ACTIONS(68), 1,
      sym__int,
    ACTIONS(72), 1,
      anon_sym_RPAREN,
    STATE(116), 1,
      sym_function_name,
    STATE(97), 2,
      sym__expr,
      sym__primary_expr,
    STATE(29), 3,
      sym_unary_op,
      sym_inv_op,
      aux_sym__primary_expr_repeat1,
    STATE(37), 3,
      sym_var_expr,
      sym_function_call,
      sym_num_literal,
  [561] = 10,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_DASH,
    ACTIONS(64), 1,
      anon_sym_BANG,
    ACTIONS(66), 1,
      sym__ident,
    ACTIONS(68), 1,
      sym__int,
    ACTIONS(74), 1,
      anon_sym_GT,
    STATE(116), 1,
      sym_function_name,
    STATE(97), 2,
      sym__expr,
      sym__primary_expr,
    STATE(29), 3,
      sym_unary_op,
      sym_inv_op,
      aux_sym__primary_expr_repeat1,
    STATE(37), 3,
      sym_var_expr,
      sym_function_call,
      sym_num_literal,
  [597] = 10,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_DASH,
    ACTIONS(64), 1,
      anon_sym_BANG,
    ACTIONS(66), 1,
      sym__ident,
    ACTIONS(68), 1,
      sym__int,
    ACTIONS(76), 1,
      anon_sym_RPAREN,
    STATE(116), 1,
      sym_function_name,
    STATE(97), 2,
      sym__expr,
      sym__primary_expr,
    STATE(29), 3,
      sym_unary_op,
      sym_inv_op,
      aux_sym__primary_expr_repeat1,
    STATE(37), 3,
      sym_var_expr,
      sym_function_call,
      sym_num_literal,
  [633] = 9,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_DASH,
    ACTIONS(64), 1,
      anon_sym_BANG,
    ACTIONS(66), 1,
      sym__ident,
    ACTIONS(68), 1,
      sym__int,
    STATE(116), 1,
      sym_function_name,
    STATE(125), 2,
      sym__expr,
      sym__primary_expr,
    STATE(29), 3,
      sym_unary_op,
      sym_inv_op,
      aux_sym__primary_expr_repeat1,
    STATE(37), 3,
      sym_var_expr,
      sym_function_call,
      sym_num_literal,
  [666] = 9,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_DASH,
    ACTIONS(64), 1,
      anon_sym_BANG,
    ACTIONS(66), 1,
      sym__ident,
    ACTIONS(68), 1,
      sym__int,
    STATE(116), 1,
      sym_function_name,
    STATE(124), 2,
      sym__expr,
      sym__primary_expr,
    STATE(29), 3,
      sym_unary_op,
      sym_inv_op,
      aux_sym__primary_expr_repeat1,
    STATE(37), 3,
      sym_var_expr,
      sym_function_call,
      sym_num_literal,
  [699] = 9,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_DASH,
    ACTIONS(64), 1,
      anon_sym_BANG,
    ACTIONS(66), 1,
      sym__ident,
    ACTIONS(68), 1,
      sym__int,
    STATE(116), 1,
      sym_function_name,
    STATE(97), 2,
      sym__expr,
      sym__primary_expr,
    STATE(29), 3,
      sym_unary_op,
      sym_inv_op,
      aux_sym__primary_expr_repeat1,
    STATE(37), 3,
      sym_var_expr,
      sym_function_call,
      sym_num_literal,
  [732] = 9,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_DASH,
    ACTIONS(64), 1,
      anon_sym_BANG,
    ACTIONS(66), 1,
      sym__ident,
    ACTIONS(68), 1,
      sym__int,
    STATE(116), 1,
      sym_function_name,
    STATE(119), 2,
      sym__expr,
      sym__primary_expr,
    STATE(29), 3,
      sym_unary_op,
      sym_inv_op,
      aux_sym__primary_expr_repeat1,
    STATE(37), 3,
      sym_var_expr,
      sym_function_call,
      sym_num_literal,
  [765] = 9,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_DASH,
    ACTIONS(64), 1,
      anon_sym_BANG,
    ACTIONS(66), 1,
      sym__ident,
    ACTIONS(68), 1,
      sym__int,
    STATE(116), 1,
      sym_function_name,
    STATE(106), 2,
      sym__expr,
      sym__primary_expr,
    STATE(29), 3,
      sym_unary_op,
      sym_inv_op,
      aux_sym__primary_expr_repeat1,
    STATE(37), 3,
      sym_var_expr,
      sym_function_call,
      sym_num_literal,
  [798] = 9,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_DASH,
    ACTIONS(64), 1,
      anon_sym_BANG,
    ACTIONS(66), 1,
      sym__ident,
    ACTIONS(68), 1,
      sym__int,
    STATE(116), 1,
      sym_function_name,
    STATE(113), 2,
      sym__expr,
      sym__primary_expr,
    STATE(29), 3,
      sym_unary_op,
      sym_inv_op,
      aux_sym__primary_expr_repeat1,
    STATE(37), 3,
      sym_var_expr,
      sym_function_call,
      sym_num_literal,
  [831] = 9,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_DASH,
    ACTIONS(64), 1,
      anon_sym_BANG,
    ACTIONS(66), 1,
      sym__ident,
    ACTIONS(68), 1,
      sym__int,
    STATE(116), 1,
      sym_function_name,
    STATE(81), 2,
      sym__expr,
      sym__primary_expr,
    STATE(29), 3,
      sym_unary_op,
      sym_inv_op,
      aux_sym__primary_expr_repeat1,
    STATE(37), 3,
      sym_var_expr,
      sym_function_call,
      sym_num_literal,
  [864] = 9,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_DASH,
    ACTIONS(64), 1,
      anon_sym_BANG,
    ACTIONS(66), 1,
      sym__ident,
    ACTIONS(68), 1,
      sym__int,
    STATE(116), 1,
      sym_function_name,
    STATE(129), 2,
      sym__expr,
      sym__primary_expr,
    STATE(29), 3,
      sym_unary_op,
      sym_inv_op,
      aux_sym__primary_expr_repeat1,
    STATE(37), 3,
      sym_var_expr,
      sym_function_call,
      sym_num_literal,
  [897] = 9,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_DASH,
    ACTIONS(64), 1,
      anon_sym_BANG,
    ACTIONS(66), 1,
      sym__ident,
    ACTIONS(68), 1,
      sym__int,
    STATE(116), 1,
      sym_function_name,
    STATE(114), 2,
      sym__expr,
      sym__primary_expr,
    STATE(29), 3,
      sym_unary_op,
      sym_inv_op,
      aux_sym__primary_expr_repeat1,
    STATE(37), 3,
      sym_var_expr,
      sym_function_call,
      sym_num_literal,
  [930] = 8,
    ACTIONS(62), 1,
      anon_sym_DASH,
    ACTIONS(64), 1,
      anon_sym_BANG,
    ACTIONS(66), 1,
      sym__ident,
    ACTIONS(68), 1,
      sym__int,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    STATE(116), 1,
      sym_function_name,
    STATE(32), 3,
      sym_var_expr,
      sym_function_call,
      sym_num_literal,
    STATE(45), 3,
      sym_unary_op,
      sym_inv_op,
      aux_sym__primary_expr_repeat1,
  [959] = 4,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    STATE(38), 4,
      sym_field_expr,
      sym_method_expr,
      sym_index_expr,
      aux_sym__primary_expr_repeat2,
    ACTIONS(80), 5,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [979] = 4,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    STATE(34), 4,
      sym_field_expr,
      sym_method_expr,
      sym_index_expr,
      aux_sym__primary_expr_repeat2,
    ACTIONS(86), 5,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [999] = 4,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    STATE(36), 4,
      sym_field_expr,
      sym_method_expr,
      sym_index_expr,
      aux_sym__primary_expr_repeat2,
    ACTIONS(86), 5,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1019] = 4,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    STATE(34), 4,
      sym_field_expr,
      sym_method_expr,
      sym_index_expr,
      aux_sym__primary_expr_repeat2,
    ACTIONS(80), 5,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1039] = 4,
    ACTIONS(90), 1,
      anon_sym_DOT,
    ACTIONS(93), 1,
      anon_sym_LBRACK,
    STATE(34), 4,
      sym_field_expr,
      sym_method_expr,
      sym_index_expr,
      aux_sym__primary_expr_repeat2,
    ACTIONS(88), 5,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1059] = 4,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    STATE(33), 4,
      sym_field_expr,
      sym_method_expr,
      sym_index_expr,
      aux_sym__primary_expr_repeat2,
    ACTIONS(96), 5,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1079] = 4,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    STATE(34), 4,
      sym_field_expr,
      sym_method_expr,
      sym_index_expr,
      aux_sym__primary_expr_repeat2,
    ACTIONS(96), 5,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1099] = 4,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    STATE(31), 4,
      sym_field_expr,
      sym_method_expr,
      sym_index_expr,
      aux_sym__primary_expr_repeat2,
    ACTIONS(98), 5,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1119] = 4,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    STATE(34), 4,
      sym_field_expr,
      sym_method_expr,
      sym_index_expr,
      aux_sym__primary_expr_repeat2,
    ACTIONS(100), 5,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1139] = 8,
    ACTIONS(7), 1,
      anon_sym_mod,
    ACTIONS(9), 1,
      anon_sym_use,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
    ACTIONS(104), 1,
      anon_sym_LF,
    STATE(66), 1,
      aux_sym_document_repeat1,
    STATE(44), 2,
      sym_item,
      aux_sym_document_repeat2,
    STATE(65), 3,
      sym_mod,
      sym_use,
      sym_let,
  [1167] = 4,
    ACTIONS(108), 1,
      anon_sym_LPAREN,
    ACTIONS(110), 1,
      anon_sym_COLON_COLON,
    STATE(83), 1,
      aux_sym_type_repeat1,
    ACTIONS(106), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1186] = 4,
    ACTIONS(114), 1,
      anon_sym_LPAREN,
    ACTIONS(116), 1,
      anon_sym_COLON_COLON,
    STATE(51), 1,
      sym_call_params,
    ACTIONS(112), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1205] = 6,
    ACTIONS(7), 1,
      anon_sym_mod,
    ACTIONS(9), 1,
      anon_sym_use,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
    STATE(43), 2,
      sym_item,
      aux_sym_document_repeat2,
    STATE(65), 3,
      sym_mod,
      sym_use,
      sym_let,
  [1227] = 6,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 1,
      anon_sym_mod,
    ACTIONS(123), 1,
      anon_sym_use,
    ACTIONS(126), 1,
      anon_sym_let,
    STATE(43), 2,
      sym_item,
      aux_sym_document_repeat2,
    STATE(65), 3,
      sym_mod,
      sym_use,
      sym_let,
  [1249] = 6,
    ACTIONS(7), 1,
      anon_sym_mod,
    ACTIONS(9), 1,
      anon_sym_use,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(129), 1,
      ts_builtin_sym_end,
    STATE(43), 2,
      sym_item,
      aux_sym_document_repeat2,
    STATE(65), 3,
      sym_mod,
      sym_use,
      sym_let,
  [1271] = 4,
    ACTIONS(133), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_BANG,
    ACTIONS(131), 3,
      anon_sym_LPAREN,
      sym__ident,
      sym__int,
    STATE(45), 3,
      sym_unary_op,
      sym_inv_op,
      aux_sym__primary_expr_repeat1,
  [1288] = 1,
    ACTIONS(39), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1298] = 3,
    ACTIONS(141), 1,
      anon_sym_SEMI,
    STATE(50), 1,
      aux_sym_let_repeat1,
    ACTIONS(139), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_mod,
      anon_sym_use,
      anon_sym_let,
  [1312] = 3,
    ACTIONS(141), 1,
      anon_sym_SEMI,
    STATE(50), 1,
      aux_sym_let_repeat1,
    ACTIONS(143), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_mod,
      anon_sym_use,
      anon_sym_let,
  [1326] = 1,
    ACTIONS(145), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1336] = 3,
    ACTIONS(149), 1,
      anon_sym_SEMI,
    STATE(50), 1,
      aux_sym_let_repeat1,
    ACTIONS(147), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_mod,
      anon_sym_use,
      anon_sym_let,
  [1350] = 1,
    ACTIONS(152), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1360] = 1,
    ACTIONS(154), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1370] = 1,
    ACTIONS(31), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1380] = 1,
    ACTIONS(156), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1390] = 3,
    ACTIONS(141), 1,
      anon_sym_SEMI,
    STATE(50), 1,
      aux_sym_let_repeat1,
    ACTIONS(158), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_mod,
      anon_sym_use,
      anon_sym_let,
  [1404] = 3,
    ACTIONS(162), 1,
      anon_sym_SEMI,
    STATE(47), 1,
      aux_sym_let_repeat1,
    ACTIONS(160), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_mod,
      anon_sym_use,
      anon_sym_let,
  [1418] = 1,
    ACTIONS(45), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1428] = 1,
    ACTIONS(13), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1438] = 1,
    ACTIONS(164), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1448] = 3,
    ACTIONS(141), 1,
      anon_sym_SEMI,
    STATE(50), 1,
      aux_sym_let_repeat1,
    ACTIONS(166), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_mod,
      anon_sym_use,
      anon_sym_let,
  [1462] = 3,
    ACTIONS(141), 1,
      anon_sym_SEMI,
    STATE(50), 1,
      aux_sym_let_repeat1,
    ACTIONS(168), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_mod,
      anon_sym_use,
      anon_sym_let,
  [1476] = 1,
    ACTIONS(170), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1486] = 1,
    ACTIONS(172), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1496] = 1,
    ACTIONS(174), 7,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1506] = 3,
    ACTIONS(178), 1,
      anon_sym_LF,
    STATE(67), 1,
      aux_sym_document_repeat1,
    ACTIONS(176), 4,
      ts_builtin_sym_end,
      anon_sym_mod,
      anon_sym_use,
      anon_sym_let,
  [1519] = 3,
    ACTIONS(182), 1,
      anon_sym_LF,
    STATE(66), 1,
      aux_sym_document_repeat1,
    ACTIONS(180), 4,
      ts_builtin_sym_end,
      anon_sym_mod,
      anon_sym_use,
      anon_sym_let,
  [1532] = 3,
    ACTIONS(104), 1,
      anon_sym_LF,
    STATE(66), 1,
      aux_sym_document_repeat1,
    ACTIONS(185), 4,
      ts_builtin_sym_end,
      anon_sym_mod,
      anon_sym_use,
      anon_sym_let,
  [1545] = 3,
    ACTIONS(189), 1,
      anon_sym_COLON_COLON,
    STATE(68), 1,
      aux_sym_type_repeat1,
    ACTIONS(187), 4,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_LPAREN,
  [1558] = 1,
    ACTIONS(192), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_mod,
      anon_sym_use,
      anon_sym_let,
  [1566] = 1,
    ACTIONS(194), 5,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym__ident,
      sym__int,
  [1574] = 1,
    ACTIONS(196), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_mod,
      anon_sym_use,
      anon_sym_let,
  [1582] = 1,
    ACTIONS(198), 5,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym__ident,
      sym__int,
  [1590] = 1,
    ACTIONS(187), 5,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COLON_COLON,
  [1598] = 5,
    ACTIONS(200), 1,
      anon_sym_LT,
    ACTIONS(202), 1,
      anon_sym_EQ,
    ACTIONS(204), 1,
      anon_sym_COLON_COLON,
    STATE(68), 1,
      aux_sym_type_repeat1,
    STATE(133), 1,
      sym_env_def,
  [1614] = 5,
    ACTIONS(200), 1,
      anon_sym_LT,
    ACTIONS(206), 1,
      anon_sym_EQ,
    ACTIONS(208), 1,
      anon_sym_COLON_COLON,
    STATE(74), 1,
      aux_sym_type_repeat1,
    STATE(123), 1,
      sym_env_def,
  [1630] = 3,
    ACTIONS(212), 1,
      anon_sym_COLON_COLON,
    STATE(76), 1,
      aux_sym_type_repeat2,
    ACTIONS(210), 2,
      anon_sym_EQ,
      anon_sym_LPAREN,
  [1641] = 3,
    ACTIONS(215), 1,
      anon_sym_COMMA,
    STATE(77), 1,
      aux_sym_env_def_repeat1,
    ACTIONS(218), 2,
      anon_sym_GT,
      anon_sym_RPAREN,
  [1652] = 3,
    ACTIONS(220), 1,
      anon_sym_LPAREN,
    ACTIONS(222), 1,
      anon_sym_COLON_COLON,
    STATE(90), 1,
      aux_sym_type_repeat2,
  [1662] = 3,
    ACTIONS(200), 1,
      anon_sym_LT,
    ACTIONS(224), 1,
      sym__ident,
    STATE(88), 1,
      sym_env_def,
  [1672] = 3,
    ACTIONS(200), 1,
      anon_sym_LT,
    ACTIONS(224), 1,
      sym__ident,
    STATE(103), 1,
      sym_env_def,
  [1682] = 3,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    ACTIONS(228), 1,
      anon_sym_RPAREN,
    STATE(94), 1,
      aux_sym_env_def_repeat1,
  [1692] = 3,
    ACTIONS(200), 1,
      anon_sym_LT,
    ACTIONS(224), 1,
      sym__ident,
    STATE(78), 1,
      sym_env_def,
  [1702] = 3,
    ACTIONS(230), 1,
      anon_sym_LPAREN,
    ACTIONS(232), 1,
      anon_sym_COLON_COLON,
    STATE(68), 1,
      aux_sym_type_repeat1,
  [1712] = 1,
    ACTIONS(234), 3,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_COLON_COLON,
  [1718] = 3,
    ACTIONS(70), 1,
      anon_sym_GT,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    STATE(77), 1,
      aux_sym_env_def_repeat1,
  [1728] = 3,
    ACTIONS(200), 1,
      anon_sym_LT,
    ACTIONS(238), 1,
      sym__ident,
    STATE(98), 1,
      sym_env_def,
  [1738] = 3,
    ACTIONS(222), 1,
      anon_sym_COLON_COLON,
    ACTIONS(240), 1,
      anon_sym_EQ,
    STATE(76), 1,
      aux_sym_type_repeat2,
  [1748] = 3,
    ACTIONS(222), 1,
      anon_sym_COLON_COLON,
    ACTIONS(240), 1,
      anon_sym_EQ,
    STATE(99), 1,
      aux_sym_type_repeat2,
  [1758] = 2,
    ACTIONS(244), 1,
      sym__int,
    ACTIONS(242), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [1766] = 3,
    ACTIONS(222), 1,
      anon_sym_COLON_COLON,
    ACTIONS(246), 1,
      anon_sym_LPAREN,
    STATE(76), 1,
      aux_sym_type_repeat2,
  [1776] = 3,
    ACTIONS(222), 1,
      anon_sym_COLON_COLON,
    ACTIONS(246), 1,
      anon_sym_LPAREN,
    STATE(100), 1,
      aux_sym_type_repeat2,
  [1786] = 3,
    ACTIONS(248), 1,
      anon_sym_mut,
    ACTIONS(250), 1,
      sym__ident,
    STATE(109), 1,
      sym_var_name,
  [1796] = 3,
    ACTIONS(252), 1,
      anon_sym_SEMI,
    ACTIONS(254), 1,
      anon_sym_COLON_COLON,
    STATE(95), 1,
      aux_sym_type_repeat1,
  [1806] = 3,
    ACTIONS(72), 1,
      anon_sym_RPAREN,
    ACTIONS(256), 1,
      anon_sym_COMMA,
    STATE(77), 1,
      aux_sym_env_def_repeat1,
  [1816] = 3,
    ACTIONS(254), 1,
      anon_sym_COLON_COLON,
    ACTIONS(258), 1,
      anon_sym_SEMI,
    STATE(68), 1,
      aux_sym_type_repeat1,
  [1826] = 1,
    ACTIONS(260), 3,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_COLON_COLON,
  [1832] = 1,
    ACTIONS(218), 3,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_RPAREN,
  [1838] = 1,
    ACTIONS(210), 3,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_COLON_COLON,
  [1844] = 3,
    ACTIONS(222), 1,
      anon_sym_COLON_COLON,
    ACTIONS(262), 1,
      anon_sym_EQ,
    STATE(76), 1,
      aux_sym_type_repeat2,
  [1854] = 3,
    ACTIONS(222), 1,
      anon_sym_COLON_COLON,
    ACTIONS(264), 1,
      anon_sym_LPAREN,
    STATE(76), 1,
      aux_sym_type_repeat2,
  [1864] = 1,
    ACTIONS(266), 3,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_COLON_COLON,
  [1870] = 3,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(270), 1,
      anon_sym_GT,
    STATE(85), 1,
      aux_sym_env_def_repeat1,
  [1880] = 3,
    ACTIONS(222), 1,
      anon_sym_COLON_COLON,
    ACTIONS(272), 1,
      anon_sym_EQ,
    STATE(87), 1,
      aux_sym_type_repeat2,
  [1890] = 1,
    ACTIONS(274), 3,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_COLON_COLON,
  [1896] = 3,
    ACTIONS(200), 1,
      anon_sym_LT,
    ACTIONS(224), 1,
      sym__ident,
    STATE(91), 1,
      sym_env_def,
  [1906] = 2,
    ACTIONS(276), 1,
      anon_sym_SEMI,
    STATE(48), 1,
      aux_sym_let_repeat1,
  [1913] = 2,
    ACTIONS(200), 1,
      anon_sym_LT,
    STATE(118), 1,
      sym_env_def,
  [1920] = 1,
    ACTIONS(278), 2,
      anon_sym_COLON,
      anon_sym_EQ,
  [1925] = 2,
    ACTIONS(280), 1,
      anon_sym_COLON,
    ACTIONS(282), 1,
      anon_sym_EQ,
  [1932] = 2,
    ACTIONS(284), 1,
      anon_sym_SEMI,
    STATE(69), 1,
      sym__close,
  [1939] = 2,
    ACTIONS(286), 1,
      sym__ident,
    STATE(117), 1,
      sym_var_name,
  [1946] = 2,
    ACTIONS(284), 1,
      anon_sym_SEMI,
    STATE(71), 1,
      sym__close,
  [1953] = 2,
    ACTIONS(288), 1,
      anon_sym_SEMI,
    STATE(61), 1,
      aux_sym_let_repeat1,
  [1960] = 2,
    ACTIONS(290), 1,
      anon_sym_SEMI,
    STATE(55), 1,
      aux_sym_let_repeat1,
  [1967] = 2,
    ACTIONS(292), 1,
      sym__ident,
    STATE(112), 1,
      sym__qual,
  [1974] = 2,
    ACTIONS(114), 1,
      anon_sym_LPAREN,
    STATE(49), 1,
      sym_call_params,
  [1981] = 2,
    ACTIONS(294), 1,
      anon_sym_COLON,
    ACTIONS(296), 1,
      anon_sym_EQ,
  [1988] = 2,
    ACTIONS(114), 1,
      anon_sym_LPAREN,
    STATE(63), 1,
      sym_call_params,
  [1995] = 2,
    ACTIONS(298), 1,
      anon_sym_SEMI,
    STATE(60), 1,
      aux_sym_let_repeat1,
  [2002] = 2,
    ACTIONS(300), 1,
      sym__ident,
    STATE(127), 1,
      sym_type,
  [2009] = 2,
    ACTIONS(300), 1,
      sym__ident,
    STATE(122), 1,
      sym_type,
  [2016] = 1,
    ACTIONS(302), 1,
      anon_sym_EQ,
  [2020] = 1,
    ACTIONS(202), 1,
      anon_sym_EQ,
  [2024] = 1,
    ACTIONS(304), 1,
      anon_sym_RPAREN,
  [2028] = 1,
    ACTIONS(306), 1,
      anon_sym_RBRACK,
  [2032] = 1,
    ACTIONS(224), 1,
      sym__ident,
  [2036] = 1,
    ACTIONS(308), 1,
      anon_sym_EQ,
  [2040] = 1,
    ACTIONS(310), 1,
      ts_builtin_sym_end,
  [2044] = 1,
    ACTIONS(312), 1,
      anon_sym_RPAREN,
  [2048] = 1,
    ACTIONS(314), 1,
      sym__int,
  [2052] = 1,
    ACTIONS(316), 1,
      sym__ident,
  [2056] = 1,
    ACTIONS(318), 1,
      sym__ident,
  [2060] = 1,
    ACTIONS(272), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 44,
  [SMALL_STATE(4)] = 87,
  [SMALL_STATE(5)] = 128,
  [SMALL_STATE(6)] = 163,
  [SMALL_STATE(7)] = 198,
  [SMALL_STATE(8)] = 233,
  [SMALL_STATE(9)] = 268,
  [SMALL_STATE(10)] = 303,
  [SMALL_STATE(11)] = 338,
  [SMALL_STATE(12)] = 373,
  [SMALL_STATE(13)] = 403,
  [SMALL_STATE(14)] = 428,
  [SMALL_STATE(15)] = 453,
  [SMALL_STATE(16)] = 489,
  [SMALL_STATE(17)] = 525,
  [SMALL_STATE(18)] = 561,
  [SMALL_STATE(19)] = 597,
  [SMALL_STATE(20)] = 633,
  [SMALL_STATE(21)] = 666,
  [SMALL_STATE(22)] = 699,
  [SMALL_STATE(23)] = 732,
  [SMALL_STATE(24)] = 765,
  [SMALL_STATE(25)] = 798,
  [SMALL_STATE(26)] = 831,
  [SMALL_STATE(27)] = 864,
  [SMALL_STATE(28)] = 897,
  [SMALL_STATE(29)] = 930,
  [SMALL_STATE(30)] = 959,
  [SMALL_STATE(31)] = 979,
  [SMALL_STATE(32)] = 999,
  [SMALL_STATE(33)] = 1019,
  [SMALL_STATE(34)] = 1039,
  [SMALL_STATE(35)] = 1059,
  [SMALL_STATE(36)] = 1079,
  [SMALL_STATE(37)] = 1099,
  [SMALL_STATE(38)] = 1119,
  [SMALL_STATE(39)] = 1139,
  [SMALL_STATE(40)] = 1167,
  [SMALL_STATE(41)] = 1186,
  [SMALL_STATE(42)] = 1205,
  [SMALL_STATE(43)] = 1227,
  [SMALL_STATE(44)] = 1249,
  [SMALL_STATE(45)] = 1271,
  [SMALL_STATE(46)] = 1288,
  [SMALL_STATE(47)] = 1298,
  [SMALL_STATE(48)] = 1312,
  [SMALL_STATE(49)] = 1326,
  [SMALL_STATE(50)] = 1336,
  [SMALL_STATE(51)] = 1350,
  [SMALL_STATE(52)] = 1360,
  [SMALL_STATE(53)] = 1370,
  [SMALL_STATE(54)] = 1380,
  [SMALL_STATE(55)] = 1390,
  [SMALL_STATE(56)] = 1404,
  [SMALL_STATE(57)] = 1418,
  [SMALL_STATE(58)] = 1428,
  [SMALL_STATE(59)] = 1438,
  [SMALL_STATE(60)] = 1448,
  [SMALL_STATE(61)] = 1462,
  [SMALL_STATE(62)] = 1476,
  [SMALL_STATE(63)] = 1486,
  [SMALL_STATE(64)] = 1496,
  [SMALL_STATE(65)] = 1506,
  [SMALL_STATE(66)] = 1519,
  [SMALL_STATE(67)] = 1532,
  [SMALL_STATE(68)] = 1545,
  [SMALL_STATE(69)] = 1558,
  [SMALL_STATE(70)] = 1566,
  [SMALL_STATE(71)] = 1574,
  [SMALL_STATE(72)] = 1582,
  [SMALL_STATE(73)] = 1590,
  [SMALL_STATE(74)] = 1598,
  [SMALL_STATE(75)] = 1614,
  [SMALL_STATE(76)] = 1630,
  [SMALL_STATE(77)] = 1641,
  [SMALL_STATE(78)] = 1652,
  [SMALL_STATE(79)] = 1662,
  [SMALL_STATE(80)] = 1672,
  [SMALL_STATE(81)] = 1682,
  [SMALL_STATE(82)] = 1692,
  [SMALL_STATE(83)] = 1702,
  [SMALL_STATE(84)] = 1712,
  [SMALL_STATE(85)] = 1718,
  [SMALL_STATE(86)] = 1728,
  [SMALL_STATE(87)] = 1738,
  [SMALL_STATE(88)] = 1748,
  [SMALL_STATE(89)] = 1758,
  [SMALL_STATE(90)] = 1766,
  [SMALL_STATE(91)] = 1776,
  [SMALL_STATE(92)] = 1786,
  [SMALL_STATE(93)] = 1796,
  [SMALL_STATE(94)] = 1806,
  [SMALL_STATE(95)] = 1816,
  [SMALL_STATE(96)] = 1826,
  [SMALL_STATE(97)] = 1832,
  [SMALL_STATE(98)] = 1838,
  [SMALL_STATE(99)] = 1844,
  [SMALL_STATE(100)] = 1854,
  [SMALL_STATE(101)] = 1864,
  [SMALL_STATE(102)] = 1870,
  [SMALL_STATE(103)] = 1880,
  [SMALL_STATE(104)] = 1890,
  [SMALL_STATE(105)] = 1896,
  [SMALL_STATE(106)] = 1906,
  [SMALL_STATE(107)] = 1913,
  [SMALL_STATE(108)] = 1920,
  [SMALL_STATE(109)] = 1925,
  [SMALL_STATE(110)] = 1932,
  [SMALL_STATE(111)] = 1939,
  [SMALL_STATE(112)] = 1946,
  [SMALL_STATE(113)] = 1953,
  [SMALL_STATE(114)] = 1960,
  [SMALL_STATE(115)] = 1967,
  [SMALL_STATE(116)] = 1974,
  [SMALL_STATE(117)] = 1981,
  [SMALL_STATE(118)] = 1988,
  [SMALL_STATE(119)] = 1995,
  [SMALL_STATE(120)] = 2002,
  [SMALL_STATE(121)] = 2009,
  [SMALL_STATE(122)] = 2016,
  [SMALL_STATE(123)] = 2020,
  [SMALL_STATE(124)] = 2024,
  [SMALL_STATE(125)] = 2028,
  [SMALL_STATE(126)] = 2032,
  [SMALL_STATE(127)] = 2036,
  [SMALL_STATE(128)] = 2040,
  [SMALL_STATE(129)] = 2044,
  [SMALL_STATE(130)] = 2048,
  [SMALL_STATE(131)] = 2052,
  [SMALL_STATE(132)] = 2056,
  [SMALL_STATE(133)] = 2060,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_num_literal, 2, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_num_literal, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_num_literal, 3, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_num_literal, 4, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_num_literal, 5, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_num_literal_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_num_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__scientific_exponent, 3, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__scientific_exponent, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary_expr, 4, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary_expr, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__primary_expr_repeat2, 2, 0, 0),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__primary_expr_repeat2, 2, 0, 0), SHIFT_REPEAT(131),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__primary_expr_repeat2, 2, 0, 0), SHIFT_REPEAT(20),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary_expr, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary_expr, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary_expr, 5, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_expr, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_expr, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(132),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(115),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(92),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__primary_expr_repeat1, 2, 0, 0),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__primary_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__primary_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__close, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 6, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_let_repeat1, 2, 0, 0),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_let_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_expr, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_index_expr, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_params, 3, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 8, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__close, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_params, 4, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 7, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 5, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_num_literal, 6, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_expr, 5, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_params, 5, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 1, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 2, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_repeat1, 2, 0, 0),
  [189] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_repeat1, 2, 0, 0), SHIFT_REPEAT(126),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mod, 3, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_op, 1, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use, 3, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inv_op, 1, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 2, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_repeat2, 2, 0, 0),
  [212] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_repeat2, 2, 0, 0), SHIFT_REPEAT(86),
  [215] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_env_def_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_env_def_repeat1, 2, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name, 3, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name, 2, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_env_def, 3, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 4, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name, 4, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [250] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__qual, 1, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__qual, 2, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_env_def, 4, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 5, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name, 5, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_env_def, 2, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 3, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_env_def, 5, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_name, 1, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [310] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_edl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
